# Generated by Django 4.1.7 on 2023-03-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quickso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='name',
            new_name='mname',
        ),
    ]
